Add shared preferences functionality
SofiaZarzabal/DataStoreApp pull request #2
Opened 2022-12-27 01:19 UTC by SofiaZarzabal

## Description
Add shared preference option with load/save data functionality.

## Evidence
![Screenshare - 2022-12-26 10_17_06 PM](https://user-images.githubusercontent.com/84337427/209596388-894f6d23-1b85-4c96-bfd6-cba65d9fd42a.gif)

2022-12-27 13:22 UTC, SartiMau requested changes

2022-12-27 13:22 UTC, SartiMau commented on app/src/main/res/layout/activity_info_manager.xml
> +        android:id="@+id/til_name"
change this id by name_container, please

2022-12-27 13:22 UTC, SartiMau commented on app/src/main/res/layout/activity_info_manager.xml
> +            android:id="@+id/tiet_name"
change this ID by name, please

2022-12-27 13:22 UTC, SartiMau commented on app/src/main/java/com/example/datastoreapp/storetype/SPStore.kt
> +    fun getName(): String = storage.getString(SP_USERNAME, "username") ?: ""
do not hardcode, please put the string "username" and "" into a constant.

2022-12-27 13:22 UTC, SartiMau commented on app/src/main/java/com/example/datastoreapp/activity/MainActivity.kt
> +        this.startActivity(Intent(this, InfoManagerActivity::class.java).apply {
From the viewModel, you still posting the states GO_TO_SHARED_PREFERENCES_VIEW, GO_TO_PROTO_DATASTORE_VIEW, and GO_TO_PREFERENCES_DATASTORE_VIEW.
I recommend keeping the states here too

2022-12-27 13:28 UTC, SartiMau commented on app/src/main/java/com/example/datastoreapp/activity/MainActivity.kt
> +        this.startActivity(Intent(this, InfoManagerActivity::class.java).apply {
Also, create a getIntent method into the companion of the InfoManagerActivity that response with the correspondent intent

2023-01-11 02:52 UTC, SartiMau requested changes

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/java/com/example/datastoreapp/fragment/SharedPreferencesFragment.kt
> +        viewModel = SharedPreferencesViewModel(SharedPreferencesStore(requireContext()))
be careful with the `requireContext()` as if it comes null you will get a crash, it is better if you ask for the context directly

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/java/com/example/datastoreapp/storetype/SharedPreferencesStore.kt
> +        const val EMPTY = ""
change this to EMPTY_STRING to be more representative

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +    <!--<Button
Why do we have all these commented code?

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +    <!--<Button
a puppy died when you made this :P

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/res/layout/fragment_preferences_data_store.xml
> +        android:text="Preferences data store"
don't hardcode, use string res

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/res/layout/fragment_proto_data_store.xml
> +        android:text="Proto data store"
don't hardcode, use string res

2023-01-11 02:52 UTC, SartiMau commented on app/src/main/res/layout/fragment_shared_preferences.xml
> +        android:text="Shared preferences"
don't hardcode, use string res

2023-01-13 19:47 UTC, SartiMau approved these changes

2023-01-19 13:38 UTC, FranciscoGaraventa approved these changes
LG

2023-01-19 13:50 UTC, merged